
#Server Configuration
server:
  shutdown: graceful
  port: 9090
  servlet:
    context-path: /keycloak

keycloak:
  token-uri: http://localhost:8080/realms/spring-boot-test/protocol/openid-connect/token
  client-id: spring-boot-authorization-code
  client-secret: 8ej8a9vvYLpTSonQ1PAmX0CO2p2ujP2y

logging:
  level:
    org.springframework.security: debug

spring:
  security:
    oauth2:
      client:
        registration:
          external:
            client-name: spring-boot-authorization-code
            client-secret: 8ej8a9vvYLpTSonQ1PAmX0CO2p2ujP2y
            client-id: spring-boot-authorization-code
            scope: openid,offline_access,profile,roles
            authorization-grant-type: authorization_code
            provider: external
        provider:
          external:
            issuer-uri: http://localhost:8080/realms/spring-boot-test
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-test
